server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 111111
        url: jdbc:mysql://127.0.0.7:3306/master
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate


